language: generic
sudo: false

branches:
  only:
    - master

before_install:
 - if [ ! -z "$EVM_EMACS" ]; then curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh; fi
 - if [ ! -z "$EVM_EMACS" ]; then evm install $EVM_EMACS --use --skip; fi

env:
 - EVM_EMACS=emacs-24.4-travis
 - EVM_EMACS=emacs-24.5-travis
 - EVM_EMACS=emacs-25.1-travis
 - EVM_EMACS=emacs-git-snapshot-travis

matrix:
  fast_finish: true
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis

script:
  - emacs -batch -l ert -l pmd.el -l pmd-tests.el -f ert-run-tests-batch-and-exit
